### ISSUE TITLE
Individual cinema page '/cinema-location'

### ISSUE THREAD

**Issue by eliazzo** [fac27/Cinesphere#12]
data ? header : query
create cinema component that renders cinema data
get screening data from example data object and pass down as props to screening component

**Comment by eliazzo** [comment]
Redirect/ link from cinema cards to cinema location need to include relevant data for conditional query

**Comment by Taha-Hassan-Git** [comment]
- [ ] h1 sizing
- [ ] info component
- [ ] image layout
- [ ] params
